<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Dell" failures="1" tests="1" name="ZavrsniProjekat" time="3.669" errors="0" timestamp="2023-10-18T20:13:51 CEST">
  <testcase classname="Tests.LoginLogoutTest" name="userCanLoginWithCookies" time="0.229">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at Tests.LoginLogoutTest.userCanLoginWithCookies(LoginLogoutTest.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- userCanLoginWithCookies -->
  <testcase classname="Tests.LoginLogoutTest" name="verifyThatUserCannotLogin" time="0.0">
    <ignored/>
  </testcase> <!-- verifyThatUserCannotLogin -->
  <testcase classname="Tests.LoginLogoutTest" name="verifyThatUserCanLogout" time="0.0">
    <ignored/>
  </testcase> <!-- verifyThatUserCanLogout -->
  <testcase classname="Tests.LoginLogoutTest" name="verifyThatUserCanLogin" time="0.0">
    <ignored/>
  </testcase> <!-- verifyThatUserCanLogin -->
</testsuite> <!-- ZavrsniProjekat -->
